# Generated by Django 3.2.4 on 2021-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('completed', models.BooleanField(default=False)),
                ('duedate', models.DateTimeField(verbose_name='due date')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=900)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('completed_by', models.CharField(default='', max_length=100)),
                ('temp', models.CharField(max_length=300)),
            ],
        ),
    ]
