# Generated by Django 3.2.4 on 2021-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token_owner',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
